// Client list page.
export const dynamic = 'force-dynamic';
import { db } from '../../../lib/db';
import { clients, auditResults } from '@pare-engine/core';
import { desc, asc, sql } from 'drizzle-orm';
import { ScoreBadge } from '../components/score-badge';
import Link from 'next/link';
interface PageProps { searchParams: Promise<Record<string, string | undefined>>; }
export default async function ClientsPage({ searchParams }: PageProps): Promise<JSX.Element> {
  const params = await searchParams;
  const sortKey = params.sort ?? 'businessName'; const sortDir = params.dir === 'desc' ? 'desc' : 'asc';
  const orderFn = sortDir === 'desc' ? desc : asc;
  const columnMap: Record<string, typeof clients.businessName> = { businessName: clients.businessName, domain: clients.domain, vertical: clients.vertical, currentScore: clients.currentScore, engagementType: clients.engagementType };
  const allClients = await db.select().from(clients).orderBy(orderFn(columnMap[sortKey] ?? clients.businessName));
  const enriched = await Promise.allSettled(allClients.map(async (c) => { const la = await db.select({ auditDate: auditResults.auditDate }).from(auditResults).where(sql`${auditResults.clientId} = ${c.id}`).orderBy(desc(auditResults.auditDate)).limit(1); return { ...c, lastAuditDate: la[0]?.auditDate ?? null }; }));
  const clientRows = enriched.filter((r): r is PromiseFulfilledResult<(typeof allClients)[0] & { lastAuditDate: Date | null }> => r.status === 'fulfilled').map((r) => r.value);
  return (<div className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">Clients</h1><p className="mt-1 text-sm text-gray-500">{clientRows.length} total</p></div>{clientRows.length === 0 ? (<div className="rounded-lg border-2 border-dashed border-gray-300 bg-white p-12 text-center"><h3 className="text-lg font-semibold text-gray-900">No clients yet</h3></div>) : (<div className="overflow-x-auto rounded-lg border border-gray-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Business</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Domain</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Vertical</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Score</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Engagement</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Last Audit</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Actions</th></tr></thead><tbody className="divide-y divide-gray-200">{clientRows.map((c) => (<tr key={c.id} className="hover:bg-gray-50"><td className="whitespace-nowrap px-6 py-4 text-sm font-medium text-gray-900">{c.businessName}</td><td className="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{c.domain}</td><td className="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{c.vertical ?? '--'}</td><td className="whitespace-nowrap px-6 py-4"><ScoreBadge score={c.currentScore} letterGrade={null} size="sm" /></td><td className="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{c.engagementType ?? '--'}</td><td className="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{c.lastAuditDate ? new Date(c.lastAuditDate).toLocaleDateString() : 'Never'}</td><td className="whitespace-nowrap px-6 py-4 text-sm"><Link href={'/admin/clients/' + c.id} className="font-medium text-[#1B2A4A]">View</Link></td></tr>))}</tbody></table></div>)}</div>);
}
