// All audits list page.
export const dynamic = 'force-dynamic';
import { db } from '../../../lib/db';
import { clients, auditResults } from '@pare-engine/core';
import { desc, count, avg, sql } from 'drizzle-orm';
import { StatCard } from '../components/stat-card';
import { ScoreBadge } from '../components/score-badge';
import Link from 'next/link';
export default async function AuditsPage(): Promise<JSX.Element> {
  const [totalR, avgR, thisMonthR] = await Promise.all([db.select({ value: count() }).from(auditResults), db.select({ value: avg(auditResults.overallScore) }).from(auditResults), db.select({ value: count() }).from(auditResults).where(sql`${auditResults.auditDate} >= date_trunc('month', CURRENT_DATE)`)]);
  const auditsRaw = await db.select().from(auditResults).orderBy(desc(auditResults.auditDate));
  const enriched = await Promise.allSettled(auditsRaw.map(async (a) => { if (!a.clientId) return { ...a, businessName: null as string | null, domain: null as string | null }; const c = await db.select({ businessName: clients.businessName, domain: clients.domain }).from(clients).where(sql`${clients.id} = ${a.clientId}`).limit(1); return { ...a, businessName: c[0]?.businessName ?? null, domain: c[0]?.domain ?? null }; }));
  const audits = enriched.filter((r): r is PromiseFulfilledResult<(typeof auditsRaw)[0] & { businessName: string | null; domain: string | null }> => r.status === 'fulfilled').map((r) => r.value);
  return (<div className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">All Audits</h1></div><div className="grid grid-cols-1 gap-6 sm:grid-cols-3"><StatCard label="Total Audits" value={totalR[0]?.value ?? 0} description="All time" /><StatCard label="Average Score" value={Math.round(Number(avgR[0]?.value ?? 0))} description="All audits" /><StatCard label="This Month" value={thisMonthR[0]?.value ?? 0} description="This month" /></div>{audits.length === 0 ? (<div className="rounded-lg border-2 border-dashed border-gray-300 bg-white p-12 text-center"><h3 className="text-lg font-semibold text-gray-900">No audits yet</h3></div>) : (<div className="overflow-x-auto rounded-lg border border-gray-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Business</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Score</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Type</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Date</th><th className="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">Actions</th></tr></thead><tbody className="divide-y divide-gray-200">{audits.map((a) => (<tr key={a.id} className="hover:bg-gray-50"><td className="whitespace-nowrap px-6 py-4"><div className="text-sm font-medium text-gray-900">{a.businessName ?? '--'}</div><div className="text-xs text-gray-500">{a.domain ?? ''}</div></td><td className="whitespace-nowrap px-6 py-4"><ScoreBadge score={a.overallScore} letterGrade={a.letterGrade} size="sm" /></td><td className="whitespace-nowrap px-6 py-4 text-sm">{a.auditType}</td><td className="whitespace-nowrap px-6 py-4 text-sm">{new Date(a.auditDate).toLocaleDateString()}</td><td className="whitespace-nowrap px-6 py-4 text-sm"><Link href={'/admin/audits/' + a.id} className="text-[#1B2A4A]">View</Link>{a.reportPdfUrl && <>{' | '}<Link href={'/api/admin/audits/' + a.id + '/pdf'} className="text-[#00D4AA]">PDF</Link></>}</td></tr>))}</tbody></table></div>)}</div>);
}
